name: eighth workflow
on:
  workflow_dispatch:
    inputs:
      titleCustom:
        description: Type the title
        required: true
        type: string
        default: "hello world"

jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: event vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
