name: eleventh workflow
on: push
env:
  ENV_VAR: "hello world"
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: event vars
        run: |
          echo $GITHUB_REF
          echo '${{ github.ref}}'
          echo '${{ env.ENV_VAR }}'
          echo $ENV_VAR
