name: fifth_workflow
on: [push, issues, pull_request]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: event vars
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
