name: fifteenth workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "first step"
      - name: math expression
        run: expr 2 + 2 > math-result.txt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: math-result
          path: math-result.txt
  second_job:
    runs-on: ubuntu-latest
    needs: first_job
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: math-result
          #path: math-result
      - name: display content
        run: |
          value=`cat math-result.txt`
          echo $value
