name: fourteenth workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache node modules
        id: cache-step
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-file
      - name: display cache
        run: echo ${{ toJson(steps.cache-step.outputs) }}
      - name: install node modules
        run: npm install
