name: Fourth workflow
on:
  workflow_run:
    workflows: ["third workflow"]
    types:
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: first_step
        run: echo "hello success !"
  failure-command:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: first_step
        run: echo "hello faild !"
