name: tenth workflow
on: push
run-name: "display"
jobs:
  run-first-command:
    runs-on: ubuntu-latest
    steps:
      - name: context to json
        id: context
        run: |
          echo Title: '${{  toJson(github)}}'
          echo runner: '${{  toJson(runner)}}'
          echo job: '${{  toJson(job)}}'
          echo step: '${{  toJson(steps)}}'
      - name: show step context
        run: |
          echo step: '${{  toJson(steps)}}'
