name: third workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "first step"
      - name: list file
        run: ls -la
        # run: qwee -as
      #-uses : actions/checkout@v4
      #- uses: actions/checkout@v4
      - name: copy flies
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/SMDesigner999/github_actions.git"
          git fetch origin
          git checkout main
      - name: list file second
        run: ls -la
