name: first_workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: first_step
        run: echo "first step"
      - name: list file
        run: ls -la
      - uses: actions/checkout@v4
      - name: list file second
        run: ls -la
