name: twelve workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    environment: "STAG"
    steps:
      - name: event vars
        run: |
          echo '${{vars.STATUS}}'  
          echo '${{secrets.PASS}}'
