name: twelve workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: event varss
        run: |
          echo '${{vars.STATUS}}'  
          echo '${{secrets.PASS}}'
